#!/bin/bash

# generate a realtime group
addgroup realtime

# update the apt database and install needed packages
apt-get update \
&& apt-get upgrade -y --with-new-pkgs \
&& apt-get install -y \
  network-manager \
  ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy \
  ros-$ROS_DISTRO-teleop-twist-keyboard \
  libwiringpi-dev \
  ament-lint \
  clang-format \
  python3-catkin-pkg \
  python3-colcon-common-extensions \
  python3-pip \
  python3-rosdep2 \
  python3-vcstool \
&& python3 -m pip install colcon-mixin pre-commit

rosdep update \
&& colcon mixin update \
&& colcon metadata update

cd /opt/ruediger2/ros2_ws
. /opt/ros/$ROS_DISTRO/setup.sh \
&& rosdep install -q -y \
  --from-paths src \
  --ignore-src

# reverse the network names to eth0 instead of enx<mac-address>
# this is automatique after a apt-get update
# https://askubuntu.com/a/1025201
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# Activate ip forward for ipv4
sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

# link libserial
ln -s /opt/ruediger2/ruediger2_control/serial_megapi/lib/serial_megapi/libserial_megapi.so /usr/local/lib/libserial_megapi.so

# activate ruediger2 service
systemctl daemon-reload
systemctl enable ruediger2.service

# clean up to reduce image size
apt-get autoremove -y && apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /opt/ruediger2/ros2_ws
