#!/bin/bash

# generate a realtime group
addgroup realtime

# update the apt database and install needed packages
apt-get update \
&& apt-get upgrade -y --with-new-pkgs \
&& apt-get install -y --no-install-recommends \
  network-manager \
  ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy \
  ros-$ROS_DISTRO-teleop-twist-keyboard \
  ament-lint \
  clang-format \
  python3-catkin-pkg \
  python3-colcon-common-extensions \
  python3-pip \
  python3-rosdep2 \
  python3-vcstool \
&& python3 -m pip install colcon-mixin pre-commit

rosdep update \
&& colcon mixin update \
&& colcon metadata update

cd /opt/stanley2/ros_ws
. /opt/ros/$ROS_DISTRO/setup.sh \
&& rosdep install -q -y \
  --from-paths src \
  --ignore-src

# reverse the network names to eth0 instead of enx<mac-address>
# this is automatique after a apt-get update
# https://askubuntu.com/a/1025201
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# Activate ip forward for ipv4
sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

# link libvmxpi
cd /usr/local/lib
ls -la
ln -fs libvmxpi_hal_cpp.so.1.3.1 libvmxpi_hal_cpp.so.1
ln -fs libvmxpi_hal_cpp.so.1 libvmxpi_hal_cpp.so
# link libgpio vmx versionspecial
ln -fs libpigpio.so.vmx_79_rebase_bugfix libpigpio.so
ln -fs libpigpio.so.1 libpigpio.so
ls -la

# activate stanley2 service
systemctl daemon-reload
systemctl enable stanley2.service

# clean up to reduce image size
apt-get autoremove -y && apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /opt/stanley2/ros_ws
