#!/bin/bash

set -e -o pipefail
echo "PINNED_CPU_FREQUENCY=${PINNED_CPU_FREQUENCY}" > /etc/default/cpu-frequency

export DEBIAN_FRONTEND=noninteractive

# Remove some packages that are likely not needed:
# - snapd: no one packages their robot apps with snap, right?
# - fwupd: I don't think we need to update devices firmware like a logitech mouse, and it also uses like 20MB of RAM...
# - cryptsetup: don't need to setup disk encryption. Also, causes build failures on some host system configurations.
# - mdadm: don't need to setup raid.
# - Stock linux kernel: for obvious reasons

# TODO: re-enable after kernel is available
#   linux-headers-raspi \
#   linux-image-raspi \
#   linux-modules-${STOCK_LINUX_VERSION}-raspi \
#   linux-headers-${STOCK_LINUX_VERSION}-raspi \
#   linux-raspi-headers-${STOCK_LINUX_VERSION} \
#   linux-image-${STOCK_LINUX_VERSION}-raspi \
#   linux-raspi \
apt-get purge --autoremove -y \
  cryptsetup \
  fwupd \
  mdadm \
  snapd \
  btrfs-progs \
  xfsprogs

# TODO: re-enable after kernel is available
# Setting up PREEMPT_RT kernel
# cd /setup
# sudo dpkg -i linux-*.deb
# rm linux-*.deb

# Disable ondemand govenor and set constant frequency
systemctl disable ondemand
systemctl enable cpu-frequency

# Disable unattended-upgrades
apt remove -y unattended-upgrades

# Remove multipath-tools, see: https://github.com/ros-realtime/ros-realtime-rpi4-image/issues/30
apt-get purge -y multipath-tools

# TODO: If specified, create an image with isolcpus already setup.

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
