#!/bin/bash

echo $PINNED_CPU_FREQUENCY > /sys/devices/system/cpu/cpu*/cpufreq/scaling_min_freq
echo $PINNED_CPU_FREQUENCY > /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
echo 1 > /sys/devices/system/cpu/cpu*/cpufreq/stats/reset
