#!/bin/bash

# Setup ROS distro and ROS
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
apt-get update
apt-get install -y ros-$ROS_DISTRO-ros-base

# Install some misc packages
apt-get install -y cpufrequtils libraspberrypi-bin rt-tests cpuset stress stress-ng python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential python3-vcstool python3-catkin-tools python3-osrf-pycommon

# Initialize & update rosdep database 
rosdep init
rosdep update

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
