#!/bin/bash

source /opt/ros/humble/setup.bash
source /opt/ruediger2/ruediger2_control/setup.bash

# export ROS_DOMAIN_ID=33 # DOMAIN ID should be in range [0,101] (included)

ros2 launch ruediger2_control_bringup ranger.online.launch.py