#!/bin/bash

set -e -o pipefail

pushd $CACHE_DIR

# Get the kernel
filename=rpi4-rt-kernel-${LINUX_RT_VERSION}.zip
if [ ! -f $filename ]; then
  wget --progress=dot -e dotbytes=10M -O $filename https://github.com/ros-realtime/linux-real-time-kernel-builder/releases/download/${LINUX_RT_VERSION}-raspi-arm64-lttng/RPI4.RT.Kernel.deb.packages.zip
fi

unzip $filename

ls -l

# These deb files will be installed by the phase1 script.
# The /setup folder in the chroot is setup by the builder.
cp linux-*.deb $CHROOT_PATH/setup/
rm linux-*.deb

popd
