#!/bin/bash

# generate a realtime group
addgroup realtime

# update the apt database and install needed packages
apt-get update \
&& apt-get upgrade -y --with-new-pkgs \
&& apt-get install -y \
  network-manager \
  ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy \
  ros-$ROS_DISTRO-teleop-twist-keyboard \
  ament-lint \
  clang-format \
  python3-catkin-pkg \
  python3-colcon-common-extensions \
  python3-pip \
  python3-rosdep2 \
  python3-vcstool \
&& python3 -m pip install colcon-mixin pre-commit vcgencmd

# install extra cameras dependencies
# TODO: Manage with rosdep in the future
apt-get install -y \
  libopencv-dev \
  ros-$ROS_DISTRO-cv-bridge \
  python3-opencv \
  libzbar-dev \
  libgflags-dev nlohmann-json3-dev libgoogle-glog-dev \
  ros-$ROS_DISTRO-image-transport ros-$ROS_DISTRO-image-publisher ros-$ROS_DISTRO-camera-info-manager

rosdep update \
&& colcon mixin update \
&& colcon metadata update

cd /opt/stanley2/ros2_ws
. /opt/ros/$ROS_DISTRO/setup.sh \
&& rosdep install -q -y \
  --from-paths src \
  --ignore-src

# install yd-lidar-SDK dependencies
sudo apt install cmake pkg-config
cd /tmp
git clone https://github.com/YDLIDAR/YDLidar-SDK.git /tmp/YDLidar-SDK
mkdir -p /tmp/YDLidar-SDK/build
cd YDLidar-SDK/build
cmake ..
make
make install

# reverse the network names to eth0 instead of enx<mac-address>
# this is automatique after a apt-get update
# https://askubuntu.com/a/1025201
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# add udev rules to get a specific tty for ydlidar
echo 'SUBSYSTEM=="tty",ATTRS{idVendor}=="10c4",ATTRS{idProduct}=="ea60",SYMLINK+="ydlidar"' > /etc/udev/rules.d/10-ydlidar-default.rules
echo 'SUBSYSTEM=="usb",ATTR{idVendor}=="2bc5",ATTR{idProduct}=="065c",GROUP:="video",SYMLINK+="gemini_e"' > /etc/udev/rules.d/10-obsensor-libusb.rules
echo 'SUBSYSTEM=="usb",ATTR{idVendor}=="2bc5",ATTR{idProduct}=="055c",GROUP:="video",SYMLINK+="gemini_e_rgb"' >> /etc/udev/rules.d/10-obsensor-libusb.rules

# Activate ip forward for ipv4
sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

# link libvmxpi
ls -lA /usr/local/lib
ln -fs libvmxpi_hal_cpp.so.1.3.1 /usr/local/lib/libvmxpi_hal_cpp.so.1
ln -fs libvmxpi_hal_cpp.so.1 /usr/local/lib/libvmxpi_hal_cpp.so
# link libgpio vmx versionspecial
ln -fs libpigpio.so.vmx_79 /usr/local/lib/libpigpio.so.1
ln -fs libpigpio.so.1 /usr/local/lib/libpigpio.so
ls -lA /usr/local/lib

# activate stanley2 service
# commented out as a requirement to humble version
systemctl daemon-reload
# systemctl enable stanley2.service
systemctl enable stanley2_vmxpi.service
systemctl enable flo_drive_joy.service

# clean up to reduce image size
apt-get autoremove -y && apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /opt/stanley2/ros2_ws
