#!/bin/bash

set -e -o pipefail

pushd $CACHE_DIR

# # Get the kernel
filename=rpi-rt-kernel-${LINUX_RT_VERSION}.zip
if [ ! -f $filename ]; then
  wget --progress=dot -e dotbytes=10M -O $filename https://github.com/shuhaowu/rt-kernel-docker-builder/releases/download/6.8.4-r11/RPI4.RT.Kernel.deb.packages.zip
fi

unzip $filename

ls -l

rm *dbg*.deb # Remove the debug debian package as it is big.

# These deb files will be installed by the phase1 script.
# The /setup folder in the chroot is setup by the builder.
cp linux-*.deb $CHROOT_PATH/setup/
rm linux-*.deb

popd
