#!/bin/bash

# generate a realtime group
addgroup realtime

# update the apt database and install needed packages
apt-get update && apt-get upgrade -y
apt-get install network-manager -y
apt-get install -y ros-$ROS_DISTRO-xacro ros-$ROS_DISTRO-ros2-control ros-$ROS_DISTRO-ros2-controllers libwiringpi-dev ros-$ROS_DISTRO-navigation2 ros-$ROS_DISTRO-nav2-bringup ros-$ROS_DISTRO-robot-localization ros-$ROS_DISTRO-v4l2-camera ros-$ROS_DISTRO-image-transport-plugins ros-$ROS_DISTRO-image-tools ros-$ROS_DISTRO-image-common

# reverse the network names to eth0 instead of enx<mac-address>
# this is automatique after a apt-get update
# https://askubuntu.com/a/1025201
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# clean up to reduce image size
apt-get autoremove -y && apt-get clean
rm -rf /var/lib/apt/lists/*
