#!/bin/bash

set -xe -o pipefail

# Setup ROS distro and ROS
export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
dpkg -i /tmp/ros2-apt-source.deb
rm /tmp/ros2-apt-source.deb

# Enable noble-updates and backports, otherwise dependency errors will happen
sed -i 's/^Suites: noble$/Suites: noble noble-updates noble-backports/' /etc/apt/sources.list.d/ubuntu.sources

apt-get update
apt-get install -y ros-$ROS_DISTRO-ros-base

# Install some misc packages
apt-get install -y cpufrequtils libraspberrypi-bin rt-tests cpuset stress stress-ng

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
